First wave of changes
aaronpeikert/repro-tutorial pull request #281
Opened 2021-11-18 10:33 UTC by cjvanlissa

2021-11-18 14:37 UTC, brandmaier requested changes

2021-11-18 14:37 UTC, brandmaier commented on manuscript.Rmd
> +  that allows anyone to access a digital research repository and reproduce all computational steps from raw data to final report, including all relevant statistical analyses, with a single command.
```suggestion
  that allows anyone to access a digital research repository and reproduce all computational steps from raw data to final report, including all statistical analyses, with a single command.
```

2021-11-19 06:12 UTC, merged

2021-11-19 06:13 UTC, aaronpeikert commented
Things I thought about while incorporating changes:

> CJ: Aaron: I don't think the key point is that users preregister the presentation of their results (tables, figures), but rather that they preregister the analysis!!!

Of course, the analysis is the main thing, but there are RDF in the presentation of results. E.g. some researchers might decide in light of small effect size to not report the effect size and concentrate on the statistical significance.
I found it interesting to learn that the FDA expects shells for tables and graphics for clinical trials for those reasons.

> Collaborating via `Git` requires the repository to be uploaded somewhere.

> CJ This is not true

How is this not true? Sure a git repo can be placed anywhere but you require shared access to that place.

2021-12-19 07:38 UTC, cjvanlissa commented
> Of course, the analysis is the main thing, but there are RDF in the presentation of results. E.g. some researchers might decide in light of small effect size to not report the effect size and concentrate on the statistical significance.
I found it interesting to learn that the FDA expects shells for tables and graphics for clinical trials for those reasons.

OK, but I think that should be explicitly clarified.

> Collaborating via Git requires the repository to be uploaded somewhere.

People could work on a shared drive, or email each other the repository.. it would be more accurate to say that collaboration is "facilitated by" using a remote git host

2021-12-20 09:26 UTC, aaronpeikert commented
@cjvanlissa Hey Casper, thanks for the input, but did you realize that the paper is out?

2021-12-20 09:33 UTC, cjvanlissa commented
Of course, but I hope that is not the end of the conversation! ;)